- name: GCE instance by Ansible
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: "{{ lookup('env', 'PROJECT_ID') }}"
      #gcp_project: 
      gcp_cred_kind: serviceaccount
      #gcp_cred_file: "{{ lookup('env', 'IAC_CREDS') }}"
      gcp_cred_file: /home/hungts1984/.config/gcloud/account.json
      zone: "us-central1-a"
      region: "us-central1"

  tasks:
   - name: create a disk
     gcp_compute_disk:
        name: disk-instance
        size_gb: 50
        source_image: projects/ubuntu-os-cloud/global/images/famiely/ubuntu-1604-lts
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
     register: disk

   - name: create a instance
     gcp_compute_instance:
         state: present
         name: test-vm
         machine_type: n1-standard-1
         disks:
         - auto_delete: 'true'
           boot: 'true'
           source: "{{ disk }}"
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         network_interfaces:
           - access_configs:
             - name: External NAT
               type: ONE_TO_ONE_NAT
     register: instance
     tags:
       - create

   - name: delete a instance
     gcp_compute_instance:
         state: absent
         name: test-vm
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
     tags:
       - delete
