- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: iac-demo-249505
      gcp_cred_kind: serviceaccount
      gcp_cred_file: ~/.config/gcloud/account.json
      zone: "us-central1-a"
      region: "us-central1"

  tasks:
   - name: create a instance
     gcp_compute_instance:
         metadata:
           istest: true
         state: present
         name: test-vm
         machine_type: n1-standard-1
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
     register: instance